project:
  type: website

website:
  title: "tidy_tweet documentation"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - tutorials.qmd
      - about.qmd
  repo-url: https://github.com/QUT-Digital-Observatory/tidy_tweet
  repo-subdir: docs
  repo-branch: quarto-tutorial
  repo-actions: source

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



